#[macro_use]
extern crate lazy_static;

use std::{
    env,
    fs::{self, File},
    io::{LineWriter, Write},
    path::{Path, PathBuf},
};

use clap::Parser;
use format::{Background, Theme};

mod color;
mod error;
mod format;
mod highlight;

#[derive(Debug, Parser)]
#[clap(author, version, about)]
pub struct Args {
    /// The input colorscheme file
    pub filename: String,
    /// Directory of generated colorscheme, default to the current working directory
    pub output: Option<String>,
    /// Overwrite the init.lua file if it already exists
    #[clap(long)]
    pub overwrite_init: bool,
}

fn main() -> Result<(), anyhow::Error> {
    let args: Args = Args::parse();

    let output = get_root_dir(args.output)?;
    let theme = format::parse_theme(&args.filename)?;

    setup_directories(&output, &theme.name)?;

    generate_default_vim_colors_file(&output, &theme.name)?;
    generate_vim_colors_file(&output, &theme.name, &theme.background)?;

    generate_palette_file(&output, &theme)?;
    generate_init(&output, theme, args.overwrite_init)?;

    Ok(())
}

fn get_root_dir(output: Option<String>) -> Result<String, anyhow::Error> {
    Ok(match output {
        Some(root) => PathBuf::from(root),
        None => match env::current_dir() {
            Ok(output) => output,
            Err(error) => return Err(error.into()),
        },
    }
    .display()
    .to_string())
}

fn setup_directories(output: &str, name: &str) -> Result<(), anyhow::Error> {
    match fs::create_dir_all(format!("{output}/lua/{name}")) {
        Ok(_) => {}
        Err(error) => return Err(error.into()),
    };

    match fs::create_dir_all(format!("{output}/colors")) {
        Ok(_) => {}
        Err(error) => return Err(error.into()),
    }

    Ok(())
}

fn generate_default_vim_colors_file(output: &str, name: &str) -> Result<(), anyhow::Error> {
    match fs::write(
        format!("{output}/colors/{name}.lua"),
        format!("require(\"{name}\").init()\n"),
    ) {
        Ok(_) => Ok(()),
        Err(error) => Err(error.into()),
    }
}

fn generate_vim_colors_file(
    output: &str,
    name: &str,
    background: &Background,
) -> Result<(), anyhow::Error> {
    match fs::write(
        format!("{output}/colors/{name}-{background}.lua"),
        format!("require(\"{name}\").init(\"{background}\")\n"),
    ) {
        Ok(_) => Ok(()),
        Err(error) => Err(error.into()),
    }
}

fn generate_palette_file(output: &str, theme: &Theme) -> Result<(), anyhow::Error> {
    let name = &theme.name;
    let background = &theme.background;

    let file = File::create(format!("{output}/lua/{name}/palette-{background}.lua"))?;
    let mut writer = LineWriter::new(file);
    writer.write_all(
        b"-- This file was generated by huey, do not edit

local M = {}

function M.set_highlights()
    local hl = vim.api.nvim_set_hl
",
    )?;

    for highlight in &theme.highlights {
        writer.write_all(highlight.as_bytes())?;
    }

    writer.write_all(
        b"
end

function M.set_globals()
",
    )?;

    for global in &theme.globals {
        writer.write_all(global.as_bytes())?;
    }

    writer.write_all(
        b"end

return M\n",
    )?;

    Ok(())
}

fn generate_init(output: &str, theme: Theme, overwrite_init: bool) -> Result<(), anyhow::Error> {
    let name = &theme.name;

    let file_path = format!("{output}/lua/{name}/init.lua");

    if !overwrite_init && Path::new(&file_path).exists() {
        return Ok(());
    }

    let file = File::create(file_path)?;
    let mut writer = LineWriter::new(file);

    writer.write_all(
        format!(
            "-- This file was generated by huey, feel free to perform edits to suit your needs.
-- It will not be overwritten unless the `--overwrite_init` is specified

local M ={{}}

function M.init(theme)
    theme = theme or vim.o.background

    vim.cmd(\"hi clear\")

    if vim.fn.exists(\"syntax_on\") then
        vim.cmd(\"syntax reset\")
    end

    vim.g.colors_name = \"{name}\"
    vim.o.termguicolors = true

    palette = require(string.format(\"{name}.palette-%s\", theme))
    palette.set_highlights()
    palette.set_globals()
end

return M\n"
        )
        .as_bytes(),
    )?;

    Ok(())
}
